### ISSUE TITLE
Adjustments for h4-h6

### ISSUE THREAD

**Issue by dlewand691** [vicompany/vertical-rhythm#1]
This is an amazing tool- thank you! What would it take to implement scaling for h4, h5, h6?

**Comment by olafthecreator** [comment]
Thanks for the compliment! Good to hear you find it helpful. To add or remove font sizes, you can adjust the variable $font-sizes in the _variables.scss like this:
```
$font-sizes: ('xs', 's', 'm', 'l', 'xl', 'xxl');
```
After that, you can change the styling of the headers in _typography.scss like this:
```
h1 { @include vertical-rhythm($font-size-xxl); }
h2 { @include vertical-rhythm($font-size-xl); }
h3 { @include vertical-rhythm($font-size-l); }
h4 { @include vertical-rhythm($font-size-m); }
h5 { @include vertical-rhythm($font-size-s); }
h6 { @include vertical-rhythm($font-size-xs); }
```
I hope this answers your question!

**Comment by dlewand691** [comment]
Thanks! WIll try that out.
